parameters:
  git_dir: .
  bin_dir: vendor/bin
grumphp:
  process_timeout: 300
  git_hook_variables:
    EXEC_GRUMPHP_COMMAND: "docker compose start php && docker compose exec -T php"
  extensions:
    - GrumphpDrupal\ExtensionLoader
  hooks_dir: ~
  ascii:
    failed: vendor/hinternet/drupal-grumphp/configs/grumphp-grumpy.txt
    succeeded: vendor/hinternet/drupal-grumphp/configs/grumphp-happy.txt
  parallel:
    enabled: false
    max_workers: 32
  fixer:
    enabled: true
    fix_by_default: true
  environment:
    paths:
      - "web"
  tasks:
    git_commit_message:
      allow_empty_message: false
      enforce_capitalized_subject: false
      enforce_no_subject_punctuations: false
      enforce_no_subject_trailing_period: true
      enforce_single_lined_subject: true
      max_subject_width: 80
      max_body_width: 80
      multiline: true
      additional_modifiers: ""
      case_insensitive: false
      matchers:
        # Custom
        Does not follow the format of conventional commits (https://www.conventionalcommits.org/en/v1.0.0/): /(^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?:([\w ])+([\s\S]*))/m

    phpstan:
      level: 5
      triggered_by:
        - php
        - inc
        - module
        - install
        - profile
        - theme
      memory_limit: "-1"
      use_grumphp_paths: true
      ignore_patterns:
        - settings.php
        - settings.local.php

    phpmd:
      report_format: text
      triggered_by: ["php"]
      whitelist_patterns:
        - /^web\/modules\/custom\/(.*)/
        - /^web\/themes\/custom\/(.*)/
        - /^web\/profiles\/custom\/(.*)/
      exclude:
        - "excluded_module"

    phpcs:
      encoding: utf-8
      triggered_by:
        - php
        - module
        - inc
        - install
        - profile
        - theme
      standard: Drupal,DrupalPractice
      whitelist_patterns:
        - web/modules/custom
        - web/themes/custom
        - web/profiles/custom
      ignore_patterns:
        - settings.php
        - settings.local.php

    phplint: ~

    jsonlint: ~

    drupalcheck: ~

    composer: ~

    composer_normalize: ~
