name: Release
on:
  push:
    branches:
      - main
      - 1.x

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency:
      group: release
      cancel-in-progress: true
    steps:
      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm install semantic-release @semantic-release/github @semantic-release/changelog @semantic-release/git
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
