name: Release
on:
  push:
    branches:
      - main
      - "*.x"
      - next
      - next-major
      - beta
      - alpha
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency:
      group: release
      cancel-in-progress: true
    steps:
      - name: Sleep for 60 seconds
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/*.x' }}
        run: sleep 60s
        shell: bash
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm install semantic-release @semantic-release/github @semantic-release/changelog @semantic-release/git
      - name: Release
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/*.x' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Dry Run Release
        if: ${{ github.ref == 'refs/heads/next' || github.ref == 'refs/heads/next-major' || github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/alpha' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --dry-run



